ContentsTree = new CTree("ContentsTree");
ContentsTree.bAutoClose = true;
ContentsTree.stTarget = "Main";
f1 = ContentsTree.AddNode(null, "General Statistics", "General_Statistics.htm");
ContentsTree.AddNode(f1, "Summary", "General_Statistics.htm#Summary");
f2 = ContentsTree.AddNode(null, "Activity Statistics", "Activity_Statistics.htm");
ContentsTree.AddNode(f2, "Daily", "Activity_Statistics.htm#Daily");
ContentsTree.AddNode(f2, "By Hour of Day", "Activity_Statistics.htm#By_Hour_of_Day");
ContentsTree.AddNode(f2, "By Day of Week", "Activity_Statistics.htm#By_Day_of_Week");
ContentsTree.AddNode(f2, "By Week", "Activity_Statistics.htm#By_Week");
ContentsTree.AddNode(f2, "By Month", "Activity_Statistics.htm#By_Month");
f3 = ContentsTree.AddNode(null, "Access Statistics", "Access_Statistics.htm");
ContentsTree.AddNode(f3, "Pages", "Access_Statistics.htm#Pages");
ContentsTree.AddNode(f3, "Files", "Access_Statistics.htm#Files");
ContentsTree.AddNode(f3, "Images", "Access_Statistics.htm#Images");
ContentsTree.AddNode(f3, "Others", "Access_Statistics.htm#Others");
ContentsTree.AddNode(f3, "Directories", "Access_Statistics.htm#Directories");
ContentsTree.AddNode(f3, "Pages per Visitor", "Access_Statistics.htm#Pages_per_Visitor");
ContentsTree.AddNode(f3, "View Time", "Access_Statistics.htm#View_Time");
ContentsTree.AddNode(f3, "Time Taken", "Access_Statistics.htm#Time_Taken");
ContentsTree.AddNode(f3, "Entry Pages", "Access_Statistics.htm#Entry_Pages");
ContentsTree.AddNode(f3, "Exit Pages", "Access_Statistics.htm#Exit_Pages");
ContentsTree.AddNode(f3, "Bounces", "Access_Statistics.htm#Bounces");
ContentsTree.AddNode(f3, "Paths", "Access_Statistics.htm#Paths");
ContentsTree.AddNode(f3, "File Types", "Access_Statistics.htm#File_Types");
ContentsTree.AddNode(f3, "Virtual Domains", "Access_Statistics.htm#Virtual_Domains");
f4 = ContentsTree.AddNode(null, "Visitors", "Visitors.htm");
ContentsTree.AddNode(f4, "Hosts", "Visitors.htm#Hosts");
ContentsTree.AddNode(f4, "Top-Level Domains", "Visitors.htm#Top_Level_Domains");
ContentsTree.AddNode(f4, "Countries", "Visitors.htm#Countries");
ContentsTree.AddNode(f4, "US States", "Visitors.htm#US_States");
ContentsTree.AddNode(f4, "Cities", "Visitors.htm#Cities");
ContentsTree.AddNode(f4, "Organizations", "Visitors.htm#Organizations");
f5 = ContentsTree.AddNode(null, "Referrers", "Referrers.htm");
ContentsTree.AddNode(f5, "Referring Sites", "Referrers.htm#Referring_Sites");
ContentsTree.AddNode(f5, "Referring URLs", "Referrers.htm#Referring_URLs");
ContentsTree.AddNode(f5, "Search Engines", "Referrers.htm#Search_Engines");
ContentsTree.AddNode(f5, "Engines and Phrases", "Referrers.htm#Engines_and_Phrases");
ContentsTree.AddNode(f5, "Search Phrases", "Referrers.htm#Search_Phrases");
ContentsTree.AddNode(f5, "Search Keywords", "Referrers.htm#Search_Keywords");
ContentsTree.AddNode(f5, "Entry Pages / Engines", "Referrers.htm#Entry_Pages___Engines");
ContentsTree.AddNode(f5, "Entry Pages / Phrases", "Referrers.htm#Entry_Pages___Phrases");
ContentsTree.AddNode(f5, "Paths / Phrases", "Referrers.htm#Paths___Phrases");
ContentsTree.AddNode(f5, "Phrases / Entry Pages", "Referrers.htm#Phrases___Entry_Pages");
ContentsTree.AddNode(f5, "Search Rankings", "Referrers.htm#Search_Rankings");
f6 = ContentsTree.AddNode(null, "Browsers", "Browsers.htm");
ContentsTree.AddNode(f6, "Browsers", "Browsers.htm#Browsers");
ContentsTree.AddNode(f6, "IE Versions", "Browsers.htm#IE_Versions");
ContentsTree.AddNode(f6, "Firefox Versions", "Browsers.htm#Firefox_Versions");
ContentsTree.AddNode(f6, "Chrome Versions", "Browsers.htm#Chrome_Versions");
ContentsTree.AddNode(f6, "Opera Versions", "Browsers.htm#Opera_Versions");
ContentsTree.AddNode(f6, "Browsers / Countries", "Browsers.htm#Browsers___Countries");
ContentsTree.AddNode(f6, "Operating Systems", "Browsers.htm#Operating_Systems");
ContentsTree.AddNode(f6, "Browsers and OS", "Browsers.htm#Browsers_and_OS");
ContentsTree.AddNode(f6, ".NET Framework", "Browsers.htm#_NET_Framework");
ContentsTree.AddNode(f6, "Spiders", "Browsers.htm#Spiders");
ContentsTree.AddNode(f6, "Spidered Pages", "Browsers.htm#Spidered_Pages");
ContentsTree.AddNode(f6, "Spider Hosts", "Browsers.htm#Spider_Hosts");
ContentsTree.AddNode(f6, "Spider Organizations", "Browsers.htm#Spider_Organizations");
f7 = ContentsTree.AddNode(null, "Errors", "Errors.htm");
ContentsTree.AddNode(f7, "Types", "Errors.htm#Types");
ContentsTree.AddNode(f7, "404 Errors", "Errors.htm#404_Errors");
ContentsTree.AddNode(f7, "Other Errors", "Errors.htm#Other_Errors");
ContentsTree.AddNode(f7, "Status Codes", "Errors.htm#Status_Codes");
document.write(ContentsTree.GetHTMLCode());